version: '3'

services:
  # PHP service
  php:
    image: php:8.1-fpm
    container_name: app
    restart: on-failure
    volumes:
      - ./back:/var/www/back
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  # Nginx service
  nginx:
    build: ./nginx
    container_name: nginx
    restart: on-failure
    volumes:
      - ./front/build:/var/www/html
    depends_on:
      - php
    ports:
      - "80:80"
    networks:
      - app-network

  # Node.js service
  node:
    image: node:latest
    container_name: my-app
    restart: on-failure
    volumes:
      - ./front:/var/www/front
    networks:
      - app-network

  # MySQL service
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: on-failure
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    networks:
      - app-network

  # Redis service
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./redis:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
