version: "3.1"
services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8000:80"
    links:
      - app
      - php

  app:
    image: node:latest
    container_name: my-app
    restart: on-failure
    working_dir: /application
    volumes:
      - ./front.build:/application
    links:
      - mysql
      - redis
    ports:
      - "9000"
    environment:
      "NODE_ENV": "development"

  mysql:
    image: mysql:5.7
    tty: true
    container_name: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  php:
    build: ./back/php
    container_name: app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www
    volumes:
      - ./back/php:/var/www
      - ./back/php/local.ini:/usr/local/etc/php/conf.d/local.ini

